services:
  api:
    image: labioquim/qsar-api:dev
    build:
      context: .
      dockerfile: apps/api/Dockerfile.dev
    command: ['yarn', 'workspace', 'api', 'start:dev']
    links:
      - database
    ports:
      - "3001:3000"
    volumes:
      - ./:/app
      - files:/files
      - /app/node_modules

  ui:
    build:
      context: .
      dockerfile: apps/ui/Dockerfile.dev
    image: labioquim/qsar-ui:dev
    command: ["yarn", "workspace", "ui", "dev"]
    ports:
      - "3000:3000"
    depends_on:
      - api
      - mailer
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/apps/ui/.next
  
  mailer:
    image: murilofuza/simple-mail:0.0.6
    env_file: .env
    ports:
      - "3002:3000"
    volumes:
      - ./emails:/templates

  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "qsar"
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    volumes:
      - redis:/data

volumes:
  database:
    driver: nfsvol
  files:
    driver: nfsvol
  redis:
    driver: nfsvol