version: "3"

services:
  api:
    image: labioquim/qsar-api:dev
    build:
      context: .
      dockerfile: apps/api/Dockerfile.dev
    command: ['yarn', 'workspace', 'api', 'start:dev']
    links:
      - database
    ports:
      - "3001:3000"
    volumes:
      - ./:/app
      - files:/files
      - /app/node_modules

  ui:
    build:
      context: .
      dockerfile: apps/ui/Dockerfile.dev
    image: labioquim/qsar-ui:dev
    command: ["yarn", "workspace", "ui", "dev"]
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/apps/ui/.next

  studio:
    build:
      context: .
      dockerfile: packages/database/Dockerfile.dev
    image: labioquim/qsar-studio:dev
    command: "sh -c 'yarn workspace database generate && yarn workspace database studio'"
    ports:
      - "5555:5555"
    volumes:
      - ./:/app
      - /app/node_modules

  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "qsar"
    volumes:
      - database:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    volumes:
      - redis:/data

volumes:
  database:
    driver: nfsvol
  files:
    driver: nfsvol
  redis:
    driver: nfsvol