version: "3"

services:
  api:
    image: labioquim/qsar-api
    build:
      context: .
      dockerfile: apps/api/Dockerfile.dev
    command: sh -c "yarn prisma generate && yarn start:dev"
    environment:
      - JWT_SECRET="supersecret"
    ports:
      - "3001:3000"
    volumes:
      - ./apps/api:/app
      - files:/files
      - /app/node_modules

  ui:
    build:
      context: .
      dockerfile: apps/ui/Dockerfile.dev
    image: labioquim/qsar-ui
    command: ["yarn", "dev"]
    environment:
      - NEXTAUTH_URL=http://localhost:3002
      - NEXTAUTH_SECRET=ssecrett
    ports:
      - "3002:3000"
    depends_on:
      - api
    volumes:
      - ./apps/ui:/app
      - /app/node_modules
      - /app/.next

  studio:
    image: labioquim/qsar-database-studio
    build:
      context: .
      dockerfile: apps/api/Dockerfile.dev
    command: sh -c "yarn prisma generate && yarn prisma studio"
    ports:
      - "5555:5555"
    volumes:
      - ./apps/api:/app
      - /app/node_modules

  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "qsar"
    volumes:
      - database:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    volumes:
      - redis:/data

volumes:
  database:
    driver: nfsvol
  files:
    driver: nfsvol
  redis:
    driver: nfsvol