FROM node:20-buster-slim AS base

# RUN apk add --no-cache procps
RUN apt update && apt install procps openssl -y

# Install dependencies only when needed
FROM base AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
# RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY apps/api/package.json yarn.lock ./
RUN yarn install

# Rebuild the source code only when needed
FROM base AS builder

COPY apps/api/bin/Mold2 /bin/Mold2

RUN chmod +x /bin/Mold2

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
